version: '3.9'

services:
  api:
    image: kdrkrgz/go-url-shortener:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      Mode: Production
      AppPort: 8080
      Domain: http://0.0.0.0:8080
      UrlExpirationTime: 1440
      CacheUrlExpiration: 60 
      ShortUrlMinLen: 4
      ShortUrlMaxLen: 8
      ExpiredUrlsDeleteHour: 00:00
      DbUri: mongodb://mongo
      DbPort: 27017
      DbName: UrlShortener
      CollectionName: Urls
      RedisHost: 0.0.0.0
      RedisPort: 6379
      RedisDb: 0
    ports:
      - "8080:8080"
    networks:
      - mongodb
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    restart: always  
    ports:
      - "27017:27017"
    networks:
      - mongodb

  redis:
    image: redis:latest
    restart: always   

networks:
    mongodb:
      driver: bridge