apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appdb
  template:
    metadata:
      labels:
        app: appdb
    spec:
      containers:
        - name: appdb
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          ports:
            - containerPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: socialize
spec:
  replicas: 2
  selector:
    matchLabels:
      app: socialize
  template:
    metadata:
      labels:
        app: socialize
    spec:
      containers:
      - name: socialize
        image: kdrkrgz/go-socialize:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: appdb
  labels:
    app: appdb
spec:
  ports:
  - port: 5432
    name: appdb
  clusterIP: None
  selector:
    app: appdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db
data:
  initDb.sql: |
    CREATE DATABASE socialize;