info:
  contact: {}
paths:
  /shortener/:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Shortener
      tags:
      - Shortener
swagger: "2.0"
